export type MapStats = {
  map: string;
  matches: number;
  wins: number;
  losses: number;
  winrate: number;
  avgKd: number;
  avgKr: number;
  avgAdr: number;
  avgHsPercent: number;
  totalEloGain: number;
  kavg: number;
  aavg: number;
  davg: number;
  longestWinStreak: number;
  longestLossStreak: number;
  last5Results: string[];
};

export type PlayerStatsFull = {
  matchesPlayed: number;
  totalWins: number;
  totalLosses: number;
  winrate: number;
  eloChange: number;
  avgKd: number;
  avgKr: number;
  avgAdr: number;
  avgHsPercent: number;
  mostKills: number;
  mostKillsMatchId: string;
  fewestKills: number;
  fewestKillsMatchId: string;
  longestWinStreak: number;
  longestLossStreak: number;
  highestKr: number;
  highestKrMatchId: string;
  lowestKr: number;
  lowestKrMatchId: string;
  highestKd: number;
  highestKdMatchId: string;
  lowestKd: number;
  lowestKdMatchId: string;
  totalEloGain: number;
  kavg: number;
  aavg: number;
  davg: number;
  highestElo: number;
  lowestElo: number;
  last5Results: string[];
  avatar: string;
  country: string;
  faceitElo: number;
  skillLevel: number;
  game_player_id: string;
  nickname: string;
  mapStats: MapStats[];
};
