# application.properties
spring.config.import=optional:file:.env.backend,optional:file:../.env.backend,optional:file:.env.backend.properties,optional:file:../.env.backend.properties
spring.profiles.active=${SPRING_PROFILE:dev}
app.events.gogo-lan.key=gogo-lan
app.events.gogo-lan.name=GOGO LAN
app.events.gogo-lan.zone-id=Europe/Copenhagen
app.events.gogo-lan.start-date=2026-04-01
app.events.gogo-lan.end-date=2026-04-06
app.events.gogo-lan.player-ids=1d51deb3-3f4a-4d9e-8494-bf8d5e280341,86df81a4-ecd1-439c-a717-7efff943f3b2,cabee4bd-4c52-4ef6-80d9-ceced8206e12,d0494eda-13bf-4d0a-801b-69a8aad4ded4,a63130d8-d99a-4699-947e-8404b7ab2722,2202482c-eec3-4fa8-9286-aa573cb6dc34,49ec6cd2-96ee-4952-b723-cd5c8c97ff31
